src/Graxei/Graxei.Apresentacao/Areas/Administrativo/Controllers/LojasController.cs
using System.Web.Mvc;
using Graxei.Aplicacao.Contrato.Consultas;
using Graxei.Aplicacao.Contrato.Transacionais;
using Graxei.Apresentacao.Areas.Administrativo.Infraestutura;
using Graxei.Apresentacao.Areas.Administrativo.Models;
using Graxei.Apresentacao.Infrastructure;
using Graxei.Modelo;
using Graxei.Transversais.ContratosDeDados;
using Graxei.Transversais.Idiomas;
using Graxei.Transversais.Comum.Excecoes;
using Graxei.Transversais.Comum.TransformacaoDados.Interface;
using System.Web;
using System.IO;
using System;
using Graxei.Transversais.ContratosDeDados.Listas;
using System.Configuration;

namespace Graxei.Apresentacao.Areas.Administrativo.Controllers
{
    public class LojasController : Controller
    {
        public LojasController(IConsultaEnderecos consultasEnderecos, IGerenciamentoLojas gerenciamentoLojas,
            IConsultasLojas consultasLojas, ITransformacaoMutua<Loja, LojaContrato> transformacaoMutuaLojas,
            IConsultaEstados consultasEstados, IConsultasListaLojas consultasListaLojas, IConsultasPlanos consultasPlanos)
        {
            _gerenciamentoLojas = gerenciamentoLojas;
            _consultasLojas = consultasLojas;
            _transformacaoMutuaLojas = transformacaoMutuaLojas;
            _consultasEstados = consultasEstados;
            _consultasEnderecos = consultasEnderecos;
            _consultasListaLojas = consultasListaLojas;
            _consultasPlanos = consultasPlanos;
        }

        #region ActionResults

        public ActionResult Index(EnderecoVistaContrato item)
        {
            var model = new LojaModel { LojaContrato = new LojaContrato(), EnderecoModel = item };
            return View("Loja", model);
        }

        [HttpGet]
        public ActionResult Editar(long idLoja)
        {
            Loja loja = _consultasLojas.Get(idLoja);
            if (loja != null)
            {
                LojaContrato lojaContrato = _transformacaoMutuaLojas.Transformar(loja);

                var model = new LojaModel { LojaContrato = lojaContrato, EnderecoModel = null };
                return View("Loja", model);
            }
            return null;
        }

        [HttpPost]
        public ActionResult NovaLojaAjax(long idLoja)
        {
            Loja loja = _consultasLojas.Get(idLoja);
            if (loja != null)
            {
                LojaContrato lojaContrato = _transformacaoMutuaLojas.Transformar(loja);

                var model = new LojaModel { LojaContrato = lojaContrato, EnderecoModel = null };
                return View("NovaLojaAjax", model);
            }
            return null;
        }

        public ActionResult Listar(int numeroPagina = 1, int tamanho = 10)
        {
            ListaLojas listaLojas = _consultasListaLojas.Get(numeroPagina, tamanho);
            return PartialView("Listar", listaLojas);
        }

        [HttpPost]
        [LimpezaSessaoNovaLoja]

        public ActionResult Salvar(Usuario usuario, LojaModel item)
        {
            if (item != null && item.LojaContrato != null && item.LojaContrato.Id > 0)
            {
                return EditarNova(usuario, item);
            }
            if (!ModelState.IsValid)
            {
                return PartialView("NovaLojaAjax", item);
            }
            LojaContrato lojaSalva;
            try
            {
                lojaSalva = _gerenciamentoLojas.Salvar(item.LojaContrato, usuario);
            }
            catch (OperacaoEntidadeException ee)
            {
                ModelState.AddModelError(string.Empty, ee.Message);
                return PartialView("NovaLojaAjax", item);
            }
            ModelState.Clear();
            item.LojaContrato = lojaSalva;
            ViewBag.OperacaoSucesso = Sucesso.LojaIncluida;
            return PartialView("Loja", item);
        }

        [HttpPost]
        [LimpezaSessaoNovaLoja]
        public ActionResult EditarNova(Usuario usuario, LojaModel item)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("NovaLojaAjax", item);
            }
            LojaContrato lojaSalva;
            try
            {
                lojaSalva = _gerenciamentoLojas.Salvar(item.LojaContrato, usuario);
                lojaSalva = _consultasLojas.GetComEnderecos(lojaSalva.Id);

                ModelState.Clear();
                item.LojaContrato = lojaSalva;

                ViewBag.OperacaoSucesso = Sucesso.LojaAtualizada;
                return PartialView("NovaLojaAjax", item);
            }
            catch (OperacaoEntidadeException ee)
            {
                ModelState.AddModelError(string.Empty, ee.Message);
                return PartialView("NovaLojaAjax", item);
            }
        }

        [HttpPost]
        public ActionResult Planos(long idLoja)
        {
            PlanoLojaModel plm = new PlanoLojaModel();
            plm.Planos = _consultasPlanos.GetPlanosAtivos();
            plm.PlanoLojaContratado = _consultasLojas.Get(idLoja).Plano;
            return PartialView("Planos", plm);
        }

        public FileContentResult GetImagem(int idLoja = 0)
        {
            if (idLoja != 0)
            {
                String caminhoImagem = ConfigurationManager.AppSettings["imagesPath"];
                byte[] file = _consultasLojas.GetImageBackground(idLoja, caminhoImagem);
                if (file != null)
                {
                    return File(file, "image/jpeg");
                }
            }

            return null;
        }

        public FileContentResult GetLogo(int idLoja = 0)
        {
            if (idLoja != 0)
            {
                String caminhoImagem = ConfigurationManager.AppSettings["imagesPath"];
                byte[] file = _consultasLojas.GetLogo(idLoja, caminhoImagem);
                if (file != null)
                {
                    return File(file, "image/jpeg");
                }
            }

            return null;
        }

        [HttpPost]
        public ActionResult AdicionarLogo(long idLoja)
        {
            Loja loja = _consultasLojas.Get(idLoja);
            if (loja != null)
            {
                return View("AdicionarLogo", loja);
            }
            return null;
        }


        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AtualizarUrl(Loja loja, long lojaId)
        {
            try
            {
                Loja lojaPer = _consultasLojas.Get(lojaId);
                lojaPer.DescricaoPaginaInicial = loja.DescricaoPaginaInicial;
                lojaPer.Url = loja.Url;
                lojaPer.HabilitarUrl = loja.HabilitarUrl;

                _gerenciamentoLojas.AtualizarUrl(lojaPer);
                loja = lojaPer;
            }
            catch (OperacaoEntidadeException ee)
            {
                ModelState.AddModelError(string.Empty, ee.Message);
                return PartialView("AdicionarUrl", loja);
            }
            ModelState.Clear();
            ViewBag.OperacaoSucesso = Sucesso.LogoAdicionadoComSucesso;
            return View("AdicionarUrl", loja);
        }
        
        public ActionResult AdicionarUrl(long idLoja)
        {
            Loja loja = _consultasLojas.Get(idLoja);
            if (loja != null)
            {
                return View("AdicionarUrl", loja);
            }
            return null;
        }

        public void Upload(long idLoja)
        {
            Loja model = null;
            try
            {
                if (Request.Files.Count > 1)
                    throw new OperacaoEntidadeException(Erros.NaoExisteImagem);
                if (Request.Files.Count <= 0)
                    throw new OperacaoEntidadeException(Erros.VariasImagensSelecionadas);

                HttpPostedFileBase file = Request.Files[0];
                if (!Directory.Exists(Server.MapPath("~/Temp/LojaImagem/"))) Directory.CreateDirectory(Server.MapPath("~/Temp/LojaImagem/"));
                String fileName = Server.MapPath("~/Temp/LojaImagem/") + Guid.NewGuid().ToString();
                file.SaveAs(fileName);
                System.IO.Path.GetExtension(file.FileName);
                model = _consultasLojas.Get(idLoja);

                String caminhoImagem = ConfigurationManager.AppSettings["imagesPath"];
                if (!Directory.Exists(caminhoImagem)) Directory.CreateDirectory(caminhoImagem);
                _gerenciamentoLojas.AdicionarBackground(model, caminhoImagem, System.IO.File.ReadAllBytes(fileName), System.IO.Path.GetExtension(file.FileName));
                System.IO.File.Delete(fileName);
            }
            catch (OperacaoEntidadeException ee)
            {
                ModelState.AddModelError(string.Empty, ee.Message);
                return;// View("AdicionarLogo", model);
            }
            ModelState.Clear();
            ViewBag.OperacaoSucesso = Sucesso.LogoAdicionadoComSucesso;
            return;// View("AdicionarLogo", model);
        }

        public void UploadLogo(long idLoja)
        {
            Loja model = null;
            try
            {
                if (Request.Files.Count > 1)
                    throw new OperacaoEntidadeException(Erros.NaoExisteImagem);
                if (Request.Files.Count <= 0)
                    throw new OperacaoEntidadeException(Erros.VariasImagensSelecionadas);

                HttpPostedFileBase file = Request.Files[0];
                String fileName = Server.MapPath("~/Temp/LojaImagem/") + Guid.NewGuid().ToString();
                if (!Directory.Exists(Server.MapPath("~/Temp/LojaImagem/"))) Directory.CreateDirectory(Server.MapPath("~/Temp/LojaImagem/"));
                file.SaveAs(fileName);
                System.IO.Path.GetExtension(file.FileName);
                model = _consultasLojas.Get(idLoja);

                String caminhoImagem = ConfigurationManager.AppSettings["imagesPath"];

src/Graxei/Graxei.Apresentacao/Controllers/LoginController.cs
using System.Web.Mvc;
using Graxei.Aplicacao.Contrato.Consultas;
using Graxei.Apresentacao.Models;
using Graxei.Modelo;
using Graxei.Transversais.Comum.Autenticacao.Interfaces;
using Graxei.Transversais.Comum.Excecoes;
//using Microsoft.Web.WebPages.OAuth;
using System.Web.Security;
using DotNetOpenAuth.GoogleOAuth2;

namespace Graxei.Apresentacao.Controllers
{
    public class LoginController : Controller
    {
        public LoginController(IConsultaLogin consultasUsuarios, IGerenciadorAutenticacao gerenciadorAutenticacao)
        {
            _consultasLogin = consultasUsuarios;
            _gerenciadorAutenticacao = gerenciadorAutenticacao;
        }

        //
        // GET: /Login/
        [AllowAnonymous]
        public ActionResult Index()
        {
            //return RedirectToAction("Autenticacao");
            Usuario usuarioAutenticado = _consultasLogin.AutenticarPorLogin("admingraxei", "graxei");
            _gerenciadorAutenticacao.Registrar(usuarioAutenticado);
            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        public ActionResult Autenticacao()
        {
            return View();
        }
        [AllowAnonymous]
        public ActionResult ContaGoogle()
        {

            return new ExternalLoginResult("Google", Url.Action("ExternalLoginCallback", new { ReturnUrl = "Home" }));
        }

        [AllowAnonymous]
        public ActionResult ExternalLoginCallback(string returnUrl)
        {
            GoogleOAuth2Client.RewriteRequest();
            //AuthenticationResult result = OAuthWebSecurity.VerifyAuthentication(Url.Action("ExternalLoginCallback", new { ReturnUrl = returnUrl }));
            //if (!result.IsSuccessful)
            //{
                return RedirectToAction("ExternalLoginFailure");
            //}

            //Usuario usuarioAutenticado = _consultasLogin.GetPorEmail(result.ExtraData["email"]);
            //if (usuarioAutenticado == null)
                throw new System.Exception("O Usuario não existe");

           // FormsAuthentication.SetAuthCookie(usuarioAutenticado.Nome, false);

            //if (OAuthWebSecurity.Login(result.Provider, result.ProviderUserId, createPersistentCookie: false))
            //{
            //    return RedirectToAction("Index", "Home");
            //}

            if (User.Identity.IsAuthenticated)
            {
                // If the current user is logged in add the new account
               // OAuthWebSecurity.CreateOrUpdateAccount(result.Provider, result.ProviderUserId, User.Identity.Name);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // User is new, ask for their desired membership name
                //string loginData = OAuthWebSecurity.SerializeProviderUserId(result.Provider, result.ProviderUserId);
                //ViewBag.ProviderDisplayName = OAuthWebSecurity.GetOAuthClientData(result.Provider).DisplayName;
                ViewBag.ReturnUrl = returnUrl;
                return RedirectToAction("Index", "Home");
            }
        }
        [AllowAnonymous]
        public ActionResult Sair()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Autenticacao(AutenticacaoModel autenticacao)
        {
            /* TODO: ver como será o tratamento de autenticação, que pode (ou poderia) ser login ou e-mail */
            try
            {
                if (!ModelState.IsValid)
                {
                    return PartialView(autenticacao);
                }
                Usuario usuarioAutenticado = _consultasLogin.AutenticarPorLogin(autenticacao.LoginOuEmail, autenticacao.Senha);
                FormsAuthentication.SetAuthCookie(usuarioAutenticado.Nome, false);

                _gerenciadorAutenticacao.Registrar(usuarioAutenticado);

            }
            catch (AutenticacaoException ae)
            {
                ViewBag.Mensagem = ae.Message;
                return PartialView(autenticacao);
            }
            return Json(new { url = Url.Action("Index", "Home") });

            /*Usuario usuarioAutenticado = _consultasLogin.AutenticarPorLogin("admingraxei", "graxei");
            Helper.SetUsuarioLogado(Session, usuarioAutenticado);
            return Json(new { url = Url.Action("Home","Administrativo") });*/
        }

        [AllowAnonymous]
        public ActionResult RedefinirSenha()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public void RedefinirSenha(object obj)
        {
        }

        private IConsultaLogin _consultasLogin;
        private IGerenciadorAutenticacao _gerenciadorAutenticacao;

        internal class ExternalLoginResult : ActionResult
        {
            public ExternalLoginResult(string provider, string returnUrl)
            {
                Provider = provider;
                ReturnUrl = returnUrl;
            }

            public string Provider { get; private set; }
            public string ReturnUrl { get; private set; }

            public override void ExecuteResult(ControllerContext context)
            {
               // OAuthWebSecurity.RequestAuthentication(Provider, ReturnUrl);
            }
        }
    }
}

src/Graxei/Graxei.Apresentacao/Controllers/ProdutosController.cs
using Graxei.Modelo;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Graxei.Aplicacao.Contrato.Consultas;
using Graxei.Transversais.Comum;

namespace Graxei.Aplicacao.Implementacao.Controllers
{
    public class ProdutosController : Controller
    {

        public ProdutosController(IConsultaFabricantes appConsultasFabricantes)
        {
            _appConsultasFabricantes = appConsultasFabricantes;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Novo()
        {
            return View();
        }

        public ActionResult Copiar()
        {
            return View();
        }

        public ActionResult Autocomplete(string term)
        {
            IList<Fabricante> fabs = null;
            if (Session[Constantes.Fabricantes] == null)
            {
                Session[Constantes.Fabricantes] = _appConsultasFabricantes.TodosNomes(); 
            }
            string[] nomes = ((IList<string>)Session[Constantes.Fabricantes]).ToArray();
            return Json(nomes, JsonRequestBehavior.AllowGet);
        }



        private readonly IConsultaFabricantes _appConsultasFabricantes;

    }
}

src/Graxei/Graxei.Apresentacao/Areas/Administrativo/Views/Home/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
}

<h4>Dashboard</h4>
<div class="row">
    <div class="col-lg-6 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-comments fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">0</div>
                        <div>Comentários</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">Ver Detalhe</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-6 col-md-6 hidden">
        <div class="panel panel-success">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-tasks fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">0</div>
                        <div>Produtos (atualização)</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">Ver Detalhe</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-6 col-md-6">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-shopping-cart fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge" id="qtdPr">-</div>
                        <div>Produtos (ativos)</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">Ver Detalhe</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-6 col-md-6 hidden">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-support fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">13</div>
                        <div>Produtos (maior preço)</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">Ver Detalhe</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>

src/Graxei/Graxei.Apresentacao/Areas/Administrativo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Graxei";
}
<div class="navbar-wrapper">
    <div class="container">
        <div class="navbar navbar-inverse navbar-fixed-top " role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Ajax.ActionLink(" raxei", "Dashboard", "Home", new { controller = "Home" }, new AjaxOptions() { UpdateTargetId = "myContent", OnBegin = "openL();", OnComplete = "closeL();foco();" }, new { @class = "navbar-brand logo" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Ajax.ActionLink("Contato", "Contato", "Home", new { controller = "Home", Area = "" }, new AjaxOptions() { UpdateTargetId = "myContent", OnBegin = "openL();", OnComplete = "closeL();" }, new { })</li>
                        <li>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <form class="navbar-form navbar-left">
                                    <div class="btn-group btn-max">
                                        <button type="button" class="btn btn-warning dropdown-toggle btn-max" data-toggle="dropdown">
                                            @User.Identity.Name
                                            <span class="caret"></span>
                                            <span class="sr-only"></span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li class="menu-a-login">
                                                @Html.ActionLink("Graxei", "Index", "Home", new { controller = "Home", area = "" }, new AjaxOptions())
                                            </li>
                                            <li class="divider"></li>
                                            <li class="menu-a-login">@Html.ActionLink("log off", "Sair", "Login", new { controller = "Login", area = "" }, new AjaxOptions())</li>
                                        </ul>
                                    </div>
                                </form>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@if (User.Identity.IsAuthenticated)
{
    <div id="openMenu" class="menu-button-open" estaaberto="false">
        <i class="glyphicon glyphicon-th-large"></i> <span>Menu</span>
    </div>
    <div id="menuAdmin" class="menu-body">
        <ul>
            <li>@Ajax.IconActionLink("glyphicon glyphicon-tower", "Lojas", "Listar", "Lojas", new { controller = "Lojas" }, new AjaxOptions() { UpdateTargetId = "myContent", OnBegin = "openL();", OnComplete = "closeL();" }, new { @class = "" })</li>
            <li>@Ajax.IconActionLink("glyphicon glyphicon-tower", "Produtos", "ListarLojas", "Produtos", new { controller = "Produtos" }, new AjaxOptions() { UpdateTargetId = "myContent", OnBegin = "openL();", OnComplete = "closeL();" }, new { @class = "" })</li>
        </ul>
    </div>
}
<div class="marketing container-body">
    <div class="container" id="myContent">
        @{Html.RenderAction("Dashboard");}
    </div>
</div>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h4>Preços</h4>
                <ul>
                    <li>@Ajax.ActionLink("Planos", "Planos", "Home", new { controller = "Home", area = "" }, new AjaxOptions() { UpdateTargetId = "myContent" }, new { })</li>
                </ul>
            </div>
            <div class="col-md-4">
                <h4>Suporte</h4>
                <ul>
                    <li>@Ajax.ActionLink("Contato", "Contato", "Home", new { controller = "Home", area = "" }, new AjaxOptions() { UpdateTargetId = "myContent" }, new { })</li>
                </ul>
            </div>
            <div class="col-md-4">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p>&copy; 2015 Graxei. &middot; <a href="#">Privacidade</a> &middot; <a href="#">Termos</a></p>
            </div>
        </div>
    </div>
</footer>
<div id="myModal"></div>
<div id="msg-display"></div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/sc")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/modal")
@Scripts.Render("~/bundles/angularjs")
@Scripts.Render("~/bundles/angularjsplugins-full")
@Scripts.Render("~/Administrativo/Endereco/js")
<script src="~/Scripts/Graxei/Administrativo/Produtos/pesquisar-produtos.js"></script>
<script>
    $(document).ready(function () {

        $.ajax({
            async: true,
            url: "@Url.Action("GetQuantidadeProdutos", "Home")",
            type: "POST",
            dataType: "json",
            success: function (data) {
                $("#qtdPr").html(data);
            }
        });
    });


</script>