src/Graxei/Graxei.Apresentacao/Areas/Administrativo/Controllers/HomeController.cs
using Graxei.Aplicacao.Contrato.Consultas;
using Graxei.Modelo;
using Graxei.Transversais.Comum;
using Graxei.Transversais.Comum.Autenticacao.Interfaces;
using System.Web.Mvc;

namespace Graxei.Apresentacao.Areas.Administrativo.Controllers
{
    public class HomeController : Controller
    {

        public HomeController(IConsultasProdutoVendedor consultasProdutoVendedor, IConsultaLogin consultasUsuarios, IGerenciadorAutenticacao gerenciadorAutenticacao)
        {
            _consultasProdutoVendedor = consultasProdutoVendedor;
            _consultasLogin = consultasUsuarios;
            _gerenciadorAutenticacao = gerenciadorAutenticacao;
        }
        //
        // GET: /Administrativo/Home/
        
        public ActionResult Index()
        {
            if (Session[Constantes.UsuarioAtual] == null && User.Identity.IsAuthenticated)
            {
                Usuario usuarioAutenticado = _consultasLogin.GetPorNome(User.Identity.Name);
                _gerenciadorAutenticacao.Registrar(usuarioAutenticado);
            }
            return View();
        }

        public ActionResult Dashboard()
        {
            return View();
        }

        public ActionResult _Index()
        {
            return PartialView();
        }


        public ActionResult GetQuantidadeProdutos()
        {
           long quantidadeProduto =  _consultasProdutoVendedor.GetQuantidadeProduto();
           return Json(quantidadeProduto, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetQuantidadeProdutosCaro()
        {
            long quantidadeProduto = _consultasProdutoVendedor.GetQuantidadeProduto();
            return Json(quantidadeProduto, JsonRequestBehavior.AllowGet);
        }

        private IConsultasProdutoVendedor _consultasProdutoVendedor;
        private IConsultaLogin _consultasLogin;
        private IGerenciadorAutenticacao _gerenciadorAutenticacao;

    }
}

src/Graxei/Graxei.Apresentacao/Areas/Teste/Controllers/HomeController.cs
using Graxei.Aplicacao.Contrato.Consultas;
using Graxei.Apresentacao.Areas.Teste.Models;
using Graxei.Modelo;
using Graxei.Transversais.Comum;
using Graxei.Transversais.Comum.Autenticacao.Interfaces;
using System;
using System.Web.Mvc;
using System.Web.Routing;

namespace Graxei.Apresentacao.Areas.Teste.Controllers
{
    public class HomeController : Controller
    {

        public HomeController(IConsultaLogin consultasUsuarios, IGerenciadorAutenticacao gerenciadorAutenticacao)
        {
            _consultasLogin = consultasUsuarios;
            _gerenciadorAutenticacao = gerenciadorAutenticacao;
        }
        //
        // GET: /Teste/Home/

        public ActionResult Index()
        {
            if (Session[Constantes.UsuarioAtual] == null && User.Identity.IsAuthenticated)
            {
                Usuario usuarioAutenticado = _consultasLogin.GetPorNome(User.Identity.Name);
                _gerenciadorAutenticacao.Registrar(usuarioAutenticado);
            }
            return View();
        }

        public ActionResult CarregarPagina(String txtRota)
        {
            String[] obj = txtRota.Split(new char[] { '?' }, StringSplitOptions.RemoveEmptyEntries);
            String[] vals = obj[0].Split(new char[] { '/' }, StringSplitOptions.RemoveEmptyEntries);


            ObjectTesteModel obm = new ObjectTesteModel();
            obm.Area = vals.Length > 2 ? vals[0] : "";
            obm.Controller = vals.Length > 2 ? vals[1] : vals[0];
            obm.View = vals.Length > 2 ? vals[2] : vals[1]; ;

            RouteValueDictionary rvd = new RouteValueDictionary();

           rvd.Add("Controller", obm.Controller);
            rvd.Add("Area", obm.Area);

            if (obj.Length > 1)
            {
                vals = obj[1].Split(new char[] { '&' }, StringSplitOptions.RemoveEmptyEntries);

                foreach (String item in vals)
                {
                    string[] splitValor = item.Split('=');
                    rvd.Add(splitValor[0], splitValor[1]);
                }
            }
            obm.Route = rvd;
            return View(obm);
        }

        private IConsultaLogin _consultasLogin;
        private IGerenciadorAutenticacao _gerenciadorAutenticacao;
    }
}

src/Graxei/Graxei.Apresentacao/Controllers/LoginController.cs
using System.Web.Mvc;
using Graxei.Aplicacao.Contrato.Consultas;
using Graxei.Apresentacao.Models;
using Graxei.Modelo;
using Graxei.Transversais.Comum.Autenticacao.Interfaces;
using Graxei.Transversais.Comum.Excecoes;
//using Microsoft.Web.WebPages.OAuth;
using System.Web.Security;
using DotNetOpenAuth.GoogleOAuth2;

namespace Graxei.Apresentacao.Controllers
{
    public class LoginController : Controller
    {
        public LoginController(IConsultaLogin consultasUsuarios, IGerenciadorAutenticacao gerenciadorAutenticacao)
        {
            _consultasLogin = consultasUsuarios;
            _gerenciadorAutenticacao = gerenciadorAutenticacao;
        }

        //
        // GET: /Login/
        [AllowAnonymous]
        public ActionResult Index()
        {
            //return RedirectToAction("Autenticacao");
            Usuario usuarioAutenticado = _consultasLogin.AutenticarPorLogin("admingraxei", "graxei");
            _gerenciadorAutenticacao.Registrar(usuarioAutenticado);
            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        public ActionResult Autenticacao()
        {
            return View();
        }
        [AllowAnonymous]
        public ActionResult ContaGoogle()
        {

            return new ExternalLoginResult("Google", Url.Action("ExternalLoginCallback", new { ReturnUrl = "Home" }));
        }

        [AllowAnonymous]
        public ActionResult ExternalLoginCallback(string returnUrl)
        {
            GoogleOAuth2Client.RewriteRequest();
            //AuthenticationResult result = OAuthWebSecurity.VerifyAuthentication(Url.Action("ExternalLoginCallback", new { ReturnUrl = returnUrl }));
            //if (!result.IsSuccessful)
            //{
                return RedirectToAction("ExternalLoginFailure");
            //}

            //Usuario usuarioAutenticado = _consultasLogin.GetPorEmail(result.ExtraData["email"]);
            //if (usuarioAutenticado == null)
                throw new System.Exception("O Usuario não existe");

           // FormsAuthentication.SetAuthCookie(usuarioAutenticado.Nome, false);

            //if (OAuthWebSecurity.Login(result.Provider, result.ProviderUserId, createPersistentCookie: false))
            //{
            //    return RedirectToAction("Index", "Home");
            //}

            if (User.Identity.IsAuthenticated)
            {
                // If the current user is logged in add the new account
               // OAuthWebSecurity.CreateOrUpdateAccount(result.Provider, result.ProviderUserId, User.Identity.Name);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // User is new, ask for their desired membership name
                //string loginData = OAuthWebSecurity.SerializeProviderUserId(result.Provider, result.ProviderUserId);
                //ViewBag.ProviderDisplayName = OAuthWebSecurity.GetOAuthClientData(result.Provider).DisplayName;
                ViewBag.ReturnUrl = returnUrl;
                return RedirectToAction("Index", "Home");
            }
        }
        [AllowAnonymous]
        public ActionResult Sair()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Autenticacao(AutenticacaoModel autenticacao)
        {
            /* TODO: ver como será o tratamento de autenticação, que pode (ou poderia) ser login ou e-mail */
            try
            {
                if (!ModelState.IsValid)
                {
                    return PartialView(autenticacao);
                }
                Usuario usuarioAutenticado = _consultasLogin.AutenticarPorLogin(autenticacao.LoginOuEmail, autenticacao.Senha);
                FormsAuthentication.SetAuthCookie(usuarioAutenticado.Nome, false);

                _gerenciadorAutenticacao.Registrar(usuarioAutenticado);

            }
            catch (AutenticacaoException ae)
            {
                ViewBag.Mensagem = ae.Message;
                return PartialView(autenticacao);
            }
            return Json(new { url = Url.Action("Index", "Home") });

            /*Usuario usuarioAutenticado = _consultasLogin.AutenticarPorLogin("admingraxei", "graxei");
            Helper.SetUsuarioLogado(Session, usuarioAutenticado);
            return Json(new { url = Url.Action("Home","Administrativo") });*/
        }

        [AllowAnonymous]
        public ActionResult RedefinirSenha()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public void RedefinirSenha(object obj)
        {
        }

        private IConsultaLogin _consultasLogin;
        private IGerenciadorAutenticacao _gerenciadorAutenticacao;

        internal class ExternalLoginResult : ActionResult
        {
            public ExternalLoginResult(string provider, string returnUrl)
            {
                Provider = provider;
                ReturnUrl = returnUrl;
            }

            public string Provider { get; private set; }
            public string ReturnUrl { get; private set; }

            public override void ExecuteResult(ControllerContext context)
            {
               // OAuthWebSecurity.RequestAuthentication(Provider, ReturnUrl);
            }
        }
    }
}

src/Graxei/Graxei.Apresentacao/Controllers/LojaController.cs
using Graxei.Aplicacao.Contrato.Consultas;
using Graxei.Apresentacao.Models;
using Graxei.Modelo;
using System;
using System.Configuration;
using System.Web.Mvc;

namespace Graxei.Apresentacao.Controllers
{
    public class LojaController : Controller
    {
        public LojaController(IConsultaEnderecos consultasEnderecos, IConsultasLojas consultasLojas,  IConsultasProdutoVendedor consultasProdutoVendedor)
        {
            _consultasEnderecos = consultasEnderecos;
            _consultasLojas = consultasLojas;
            _consultasProdutoVendedor = consultasProdutoVendedor;
        }
        //
        // GET: /Loja/

        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult VerLoja(long idEndereco)
        {
            Endereco endereco = _consultasLojas.GetEnderecoComTelefones(idEndereco);
            EnderecoModel em = new EnderecoModel();
            em.Endereco = endereco;
            return View(em);
        }

        [AllowAnonymous]
        public ActionResult IndexPaginaLoja(Loja loja)
        {

            return View(loja);
        }

        public ActionResult GetQuantidadeProdutos(long lojaId)
        {
            long quantidadeProduto = _consultasProdutoVendedor.GetQuantidadeProduto(lojaId);
            return Json(quantidadeProduto, JsonRequestBehavior.AllowGet);
        }

        public FileContentResult GetImagem(int idLoja = 0)
        {
            if (idLoja != 0)
            {
                String caminhoImagem = ConfigurationManager.AppSettings["imagesPath"];
                byte[] file = _consultasLojas.GetImageBackground(idLoja, caminhoImagem);
                if (file != null)
                {
                    return File(file, "image/jpeg");
                }
            }

            return null;
        }

        public FileContentResult GetLogo(int idLoja = 0)
        {
            if (idLoja != 0)
            {
                String caminhoImagem = ConfigurationManager.AppSettings["imagesPath"];
                byte[] file = _consultasLojas.GetLogo(idLoja, caminhoImagem);
                if (file != null)
                {
                    return File(file, "image/jpeg");
                }
            }

            return null;
        }
        
        public ActionResult Produtos(Loja loja)
        {
            return View(loja);
        }

        private IConsultaEnderecos _consultasEnderecos;
        private IConsultasLojas _consultasLojas;
        private IConsultasProdutoVendedor _consultasProdutoVendedor;
    }
}

src/Graxei/Graxei.Apresentacao/Views/Home/Error404.cshtml
@{
    ViewBag.Title = "Graxei";
}
@model String
@Scripts.Render("~/bundles/jquery")
<div class="navbar-wrapper">
    <div class="container">
        <div class="navbar navbar-inverse navbar-fixed-top " role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Ajax.ActionLink(" raxei", "_Index", "Home", new { controller = "Home" }, new AjaxOptions() { UpdateTargetId = "myContent" }, new { @class = "navbar-brand logo" })
                </div>
                <div class="navbar-collapse collapse">
                    @using (Ajax.BeginForm("Pesquisar", "Home", new { Controller = "Home" }, new AjaxOptions() { UpdateTargetId = "myContent", HttpMethod = "GET", OnBegin = "openL();", OnComplete = "closeL(); teste();" }, new { @class = "navbar-form navbar-left", role = "search", id = "fq" }))
                    {	  
                        <div class="input-group nav-search">
                            @Html.TextBox("q", Model, null, new { @class = "form-control ", placeholder = @Graxei.Transversais.Idiomas.Rotulos.Pesquisar, id = "q", mozactionhint = "search" })
                            <span class="input-group-btn">
                                <button class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                            </span>
                        </div>
                    }
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Ajax.ActionLink("Sobre", "_Sobre", "Home", new { controller = "Home" }, new AjaxOptions() { UpdateTargetId = "myModal" }, new { })</li>
                        <li>@Ajax.ActionLink("Contato", "Contato", "Home", new { controller = "Home" }, new AjaxOptions() { UpdateTargetId = "myContent" }, new { })</li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>
                                <form class="navbar-form navbar-left" role="search">
                                    <div class="btn-group btn-max">
                                        <button type="button" class="btn btn-warning dropdown-toggle btn-max" data-toggle="dropdown">
                                            @User.Identity.Name
                                            <span class="caret"></span>
                                            <span class="sr-only"></span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li class="menu-a-login">@Html.ActionLink("Administrador", "Index", "Home", new { controller = "Home", area = "Administrativo" }, new AjaxOptions())
                                            </li>
                                            <li class="divider"></li>
                                            <li class="menu-a-login">@Html.ActionLink("log off", "Sair", "Login", new { controller = "Login" }, new AjaxOptions())</li>
                                        </ul>
                                    </div>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li>
                                <form class="navbar-form navbar-left" role="search">
                                    @Ajax.ActionLink("login", "Autenticacao", "Login", new { controller = "Login" }, new AjaxOptions() { UpdateTargetId = "myModal", OnSuccess = "login" }, new { id = "loginId", @class = "btn btn-success btn-max" })
                                </form>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@if (User.Identity.IsAuthenticated)
{
    <div id="openMenu" class="menu-button-open" estaaberto="false">
        <i class="glyphicon glyphicon-th-large"></i>
    </div>
    <div id="menuAdmin" class="menu-body">
        <ul>
        </ul>
    </div>
}
<div class="marketing container-body" id="myContent">
    @if (ViewBag.loja == null)
    {   
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <img src="~/Content/imagens/404.svg" class="img-60" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h2>
                        <p class="text-center">
                            : ( Página não encontrada.
                        </p>
                    </h2>
                    <p class="text-center">
                        A pagina que digitou não existe. Verifique se o caminho digitado está correto e tente novamente
                    </p>
                </div>
            </div>
        </div>
    }
    else
    {
        Html.RenderAction("IndexPaginaLoja", "Loja", new { Loja = (Graxei.Modelo.Loja)ViewBag.loja });
    }
</div>
<p class="pull-right"><a href="#" class="btn btn-default" data-toggle="tooltip" title="Ir para o topo"><i class="glyphicon glyphicon-chevron-up"></i></a></p>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h4>Preços</h4>
                <ul>
                    <li>@Ajax.ActionLink("Planos", "Planos", "Home", new { controller = "Home" }, new AjaxOptions() { UpdateTargetId = "myContent" }, new { })</li>
                    <li>@Ajax.ActionLink("Anuncie Aqui", "ContatoAnuncioModal", "Home", new { controller = "Home" }, new AjaxOptions() { UpdateTargetId = "myModal" }, new { })</li>
                </ul>
            </div>
            <div class="col-md-4">
                <h4>Suporte</h4>
                <ul>
                    <li>@Ajax.ActionLink("Contato", "Contato", "Home", new { controller = "Home" }, new AjaxOptions() { UpdateTargetId = "myContent" }, new { })</li>
                </ul>
            </div>
            <div class="col-md-4">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p>&copy; 2014 Graxei. &middot; <a href="#">Privacidade</a> &middot; <a href="#">Termos</a></p>
            </div>
        </div>
    </div>


</footer>
<div id="myModal"></div>
<div id="msg-display"></div>
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/sc")
@Scripts.Render("~/bundles/modal")
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-56830058-1', 'auto');
    ga('send', 'pageview');

    $(document).ready(function () {
        $.getJSON("http://www.telize.com/geoip?callback=?",
            function (json) {
                $.ajax({
                    type: "POST",
                    url: "Home/SetRegionIP",
                    data: { pais: json.country, cidade: json.city, regiao: json.region_code }
                });
            }
        );

        $("#openMenu").on("click", function () {
            $("#menuAdmin").toggle();

            if ($("#openMenu").attr("estaAberto") === "true") {
                $("#openMenu").css("left", "0em");
            } else {
                $("#openMenu").css("left", "15em");
            }

            $("#openMenu").attr("estaAberto", $("#openMenu").attr("estaAberto") === "false")
        });
    });

    
</script>

@if (ViewBag.q != null)
{
    <script>
        $(document).ready(function () {
            var q = "@ViewBag.q";
            $("#fq").submit();
        });
    </script>
}

src/Graxei/Graxei.Apresentacao/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Graxei";
}
@model String
@Scripts.Render("~/bundles/jquery")
<div class="navbar-wrapper">
    <div class="container">
        <div class="navbar navbar-inverse navbar-fixed-top " role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Ajax.ActionLink("Graxei", "_Index", "Home", new { controller = "Home" }, new AjaxOptions() { UpdateTargetId = "myContent" }, new { @class = "navbar-brand logo" })
                </div>
                <div class="navbar-collapse collapse">
                    @using (Ajax.BeginForm("Pesquisar", "Home", new { Controller = "Home" }, new AjaxOptions() { UpdateTargetId = "myContent", HttpMethod = "GET", OnBegin = "openL();", OnComplete = "closeL(); teste();" }, new { @class = "navbar-form navbar-left", role = "search", id = "fq" }))
                    {
                        <div class="input-group nav-search">
                            @Html.Hidden("lojaNome")
                            <div class="label-search" style="visibility:hidden">
                                <span id="lbl-loja" class="label label-warning">
                                    <a href="javascript:RemoverLoja()"><span id="lbl-loja-nome"></span> [x]</a>
                                </span>
                            </div> 
                            @Html.TextBox("q", Model, null, new { @class = "form-control ", placeholder = @Graxei.Transversais.Idiomas.Rotulos.Pesquisar, id = "q", mozactionhint = "search" })
                            <span class="input-group-btn">
                                <button class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                            </span>
                        </div>
                    }
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Ajax.ActionLink("Sobre", "_Sobre", "Home", new { controller = "Home" }, new AjaxOptions() { UpdateTargetId = "myModal" }, new { })</li>
                        <li>@Ajax.ActionLink("Contato", "Contato", "Home", new { controller = "Home" }, new AjaxOptions() { UpdateTargetId = "myContent" }, new { })</li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>
                                <form class="navbar-form navbar-left" role="search">
                                    <div class="btn-group btn-max">
                                        <button type="button" class="btn btn-warning dropdown-toggle btn-max" data-toggle="dropdown">
                                            @User.Identity.Name
                                            <span class="caret"></span>
                                            <span class="sr-only"></span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li class="menu-a-login">
                                                @Html.ActionLink("Administrador", "Index", "Home", new { controller = "Home", area = "Administrativo" }, new AjaxOptions())
                                            </li>
                                            <li class="divider"></li>
                                            <li class="menu-a-login">@Html.ActionLink("log off", "Sair", "Login", new { controller = "Login" }, new AjaxOptions())</li>
                                        </ul>
                                    </div>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li>
                                <form class="navbar-form navbar-left" role="search">
                                    @Ajax.ActionLink("login", "Autenticacao", "Login", new { controller = "Login" }, new AjaxOptions() { UpdateTargetId = "myModal" }, new { @class = "btn btn-success btn-maxZ", id = "loginId" })
                                </form>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="marketing container-body" id="myContent">
    @if (ViewBag.loja == null)
    {
        Html.RenderPartial("_Index");
    }
    else
    {
        Html.RenderAction("IndexPaginaLoja", "Loja", new { Loja = (Graxei.Modelo.Loja)ViewBag.loja });
    }
</div>
<p class="pull-right"><a href="#" class="btn btn-default" data-toggle="tooltip" title="Ir para o topo"><i class="glyphicon glyphicon-chevron-up"></i></a></p>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h4>Preços</h4>
                <ul>
                    <li>@Ajax.ActionLink("Planos", "Planos", "Home", new { controller = "Home" }, new AjaxOptions() { UpdateTargetId = "myContent" }, new { })</li>
                    <li>@Ajax.ActionLink("Anuncie Aqui", "ContatoAnuncioModal", "Home", new { controller = "Home" }, new AjaxOptions() { UpdateTargetId = "myModal" }, new { })</li>
                </ul>
            </div>
            <div class="col-md-4">
                <h4>Suporte</h4>
                <ul>
                    <li>@Ajax.ActionLink("Contato", "Contato", "Home", new { controller = "Home" }, new AjaxOptions() { UpdateTargetId = "myContent" }, new { })</li>
                </ul>
            </div>
            <div class="col-md-4">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p>&copy; 2015 Graxei. &middot; <a href="#">Privacidade</a> &middot; <a href="#">Termos</a></p>
            </div>
        </div>
    </div>


</footer>
<div id="myModal"></div>
<div id="msg-display"></div>
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/sc")
@Scripts.Render("~/bundles/modal")
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-56830058-1', 'auto');
    ga('send', 'pageview');

    $(document).ready(function () {
        $.getJSON("http://www.telize.com/geoip?callback=?",
            function (json) {
                $.ajax({
                    type: "POST",
                    url: "Home/SetRegionIP",
                    data: { pais: json.country, cidade: json.city, regiao: json.region_code }
                });
            }
        );

        $("#openMenu").on("click", function () {
            $("#menuAdmin").toggle();

            if ($("#openMenu").attr("estaAberto") === "true") {
                $("#openMenu").css("left", "0em");
            } else {
                $("#openMenu").css("left", "15em");
            }

            $("#openMenu").attr("estaAberto", $("#openMenu").attr("estaAberto") === "false")
        });
    });
</script>

@if (ViewBag.q != null)
{
    <script>
        $(document).ready(function () {
            var q = "@ViewBag.q";

            var idxLoja = q.toLowerCase().indexOf("loja:");

            var newurl = window.location.protocol + "//" + window.location.host /*+ window.location.pathname */ + '?q=@ViewBag.q';
            if (idxLoja <= 0 && sessionStorage.getItem("lojaNome_graxei") != "") {
                newurl = window.location.protocol + "//" + window.location.host /*+ window.location.pathname */ +
                    '?q=@ViewBag.q' + ' loja:' + sessionStorage.getItem("lojaNome_graxei");
            }
            window.history.pushState({ path: newurl }, '', newurl);

            if (idxLoja >= 0) {
                var idxLojaFim = q.toLowerCase().indexOf(" ", idxLoja)
                var loja = q.substring(idxLoja + 5);

                if (idxLojaFim > 0) {
                    loja = q.substring(idxLoja + 5, idxLojaFim);
                }
                sessionStorage.setItem("lojaNome_graxei", loja);
                $("#q").val(q.toLowerCase().replace("loja:" + loja, "").trim());
            }

            $("#lojaNome").val(sessionStorage.getItem("lojaNome_graxei"));

            var lojaApresentacao = sessionStorage.getItem("lojaNome_graxei");
            if (lojaApresentacao.length > 4) {
                lojaApresentacao = lojaApresentacao.substr(0, 4) + "...";
            }
            $("#lbl-loja-nome").text(lojaApresentacao);
            if (sessionStorage.getItem("lojaNome_graxei") != "") {
                $(".label-search").css("visibility", "visible");
            }
            $("#q").val(q);

            $("#fq").submit();
        });
    </script>
}

src/Graxei/Graxei.Apresentacao/Views/Home/SemResultado.cshtml
@model Graxei.Apresentacao.Models.PesquisarModel
<div class="alert alert-danger" role="alert">
    <div class="row">
        <div class="col-md-12">
            <strong>@Info.SemResultadoPesquisa</strong>
        </div>
    </div>
</div>